- src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-slavesUser.html
Add the ability to configure mesos slave username instead of
using the same user that runs the server.
> Add a configuration setting for mesos slave user

- src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
This is to resolve issue https://github.com/jenkinsci/mesos-plugin/issues/109
> Reverted explicit setting of hostname for (default) host networking mode

- .gitignore
- pom.xml
- src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
- src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java
There's an infinite loop if the offer provides a single port mapping, where the begin = 31000 and the end = 31000. The inner while loop will never execute causing an infinite loop which effectively blocks JenkinsScheduler and causes a lock up in Jenkins
> Fix infinite loop in the port mapping code

- src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly
Based on https://github.com/jenkinsci/mesos-plugin/pull/69 I've implemented a mergeable Version for the support of privileged mode for docker containers.
> Docker Privileged Mode Support

- src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
Fix issue https://github.com/jenkinsci/mesos-plugin/issues/137
> Fix java.lang.NullPointerException with privileged mode

- src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
1) When an offer is presented to start a task that just finished
2) When the plugin kills a task and then launches another one because it was in the request queue
> Fix cases where you may end up with orphaned docker containers on Mesos.

- src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosSlave.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly
This PR adds the possibility to configure the slave mode in the Slave Info section. Should Fix #134
> Add support for slave usage mode

- pom.xml
- src/main/java/org/jenkinsci/plugins/mesos/MesosRetentionStrategy.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosSlave.java
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-idleTerminationMinutes.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosSlave/configure-entries.jelly
- src/main/resources/org/jenkinsci/plugins/mesos/MesosSlave/help-idleTerminationMinutes.html
- src/test/java/org/jenkinsci/plugins/mesos/MesosRetentionStrategyTest.java
This PR allows to indicate that the instance should never be automatically terminated when the value of "Idle Termination Minutes" field is equal to 0.
> A value of zero indicates that the instance should never be automatically terminated

- src/main/resources/org/jenkinsci/plugins/mesos/MesosSlave/newInstanceDetail.jelly
- src/main/resources/org/jenkinsci/plugins/mesos/MesosSlave/newInstanceDetail.properties
Add text to dissuade usage of the /computer/new endpoint.
> Quality of life improvements for newbies.

- src/main/java/org/jenkinsci/plugins/mesos/MesosImpl.java
The current synchronized on MesosImpl method are pointless since what we are looking for is to lock access to JenkinsScheduler.
@reviewbybees 
```
thread-deadlock : [Computer.threadPoolForRemoting [#4] locked on java.util.concurrent.locks.ReentrantLock$NonfairSync@7991f96c (owned by jenkins.util.Timer [#5]):
at sun.misc.Unsafe.park(Native Method)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
at …
```
> Fix a deadlock case.

- src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
> Fix decline offer

- src/main/java/org/jenkinsci/plugins/mesos/MesosCleanupThread.java
Printing messages every minute at INFO level is too much
@reviewbybees
> Reduce log verbosity

- src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java
Same thing goes for hashCode, althugh not wrong can be improved to consider all fields
@reviewbybees
> equals method is wrong, does not consider object fields

- src/main/resources/index.jelly
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly
- src/main/resources/org/jenkinsci/plugins/mesos/MesosSlave/configure-entries.jelly
- src/main/resources/org/jenkinsci/plugins/mesos/MesosSlave/newInstanceDetail.jelly
Test fail in newer jenkins versions without it
@reviewbybees
> Add escape-by-default to jelly files

- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-checkpoint.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-containerPath.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-containerPort.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-declineOfferDuration.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-description.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-dockerForcePullImage.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-dockerImage.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-dockerPrivilegedMode.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-executorCpus.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-executorMem.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-frameworkName.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-hostPath.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-hostPort.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-labelString.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-maxExecutors.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-networking.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-onDemandRegistration.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-protocol.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-slaveAttributes.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-slaveCpus.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-slaveMem.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-type.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-volume.readOnly.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-volumes.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosSingleUseSlave/help.html
> Add inline help and removed unnecessary field entries.

- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-executorMem.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-jvmArgs.html
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-maxExecutors.html
> Improve field docs

- pom.xml
- src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosAdministrativeMonitor.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosHealthCheck.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosHealthCheckProvider.java
- src/main/resources/org/jenkinsci/plugins/mesos/MesosAdministrativeMonitor/message.jelly
> Add an administrative monitor to notify if mesos slave provisioning couldn't be done.

- README.md
Changed to working link at agent-recovery from slave-recovery.
> Updated checkpoint docs 

- src/main/java/org/jenkinsci/plugins/mesos/MesosComputerLauncher.java
Fix for https://github.com/jenkinsci/mesos-plugin/issues/269
> Support for Jenkins 2.26+ which enforces JNLPLauncher

- README.md
- pom.xml
- src/main/java/org/jenkinsci/plugins/mesos/MesosSingleUseSlave.java
Convert MesosSingleUseSlave to a SimpleBuildWrapper so that it may be used from Pipeline scripts
Fixes #262
> Pipeline support for MesosSingleUseSlave

- pom.xml
We want to avoid this:
@reviewbybees, specially, @Vlatombe
> Move to HTTPS and add a plugin description

- src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
- src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java
This commit introduces the feature for the frameworks registered by Jenkins to ignore
offers having an unavailability (maintenance primitive) set.
The offers are only ignored when the current time is between the start and end time (start + duration)
of the unavailability.
Issue: https://github.com/jenkinsci/mesos-plugin/issues/216
> Introduce support for Mesos maintenance primitives

- src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java
> Fix always restarting mesos cloud with multiple frameworks

- Jenkinsfile
- pom.xml
Just hit some issues while running PCT for JEP-200.
@reviewbybees
> Update Parent POM and fix dependencies to make it runnable in PCT

- README.md
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-master.html
More details reg. Mesos master url configuration of the Mesos plugin (address Zookeeper syntax)
Question has been asked several times in Issues, maybe it is better to document it:
#327 
#306
> [Doc] Mesos master url configuration with Zookeeper

- src/main/java/org/jenkinsci/plugins/mesos/listener/MesosRunListener.java
If we run Jenkins slave in docker container, we always get hostname as below
Mesos slave(hostname): 172.18.0.1
I have fixed the same. Please review it.
> Fix for logging mesos slave hostname

- src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
- src/main/java/org/jenkinsci/plugins/mesos/Mesos.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosComputerLauncher.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosSlave.java
- src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java
* Track per agent offer metrics
* Add better timing metrics
* Adding logging to verify actual timeframe of executor launch
> Enhance metrics (#14)

- .github/workflows/maven.yml
Tests PRs by running `mvn package`.
> Integrated with GitHub Actions.

- src/main/java/org/jenkinsci/plugins/mesos/MesosAdministrativeMonitor.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosHealthCheck.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosHealthCheckProvider.java
- src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly
- src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-enableMetricsHealthcheck.html
- src/test/java/org/jenkinsci/plugins/mesos/MesosCloudTest.java
- src/test/java/org/jenkinsci/plugins/mesos/MesosHealthCheckProviderTest.java
- src/test/java/org/jenkinsci/plugins/mesos/MesosHealthCheckTest.java
New checkbox in "advanced" section:
> Make it possible to disable Metrics healthcheck - close #321

- README.md
- build.gradle
- src/main/java/org/jenkinsci/plugins/mesos/MesosAgentSpecTemplate.java
- src/main/java/org/jenkinsci/plugins/mesos/api/LaunchCommandBuilder.java
- src/main/java/org/jenkinsci/plugins/mesos/api/RunTemplateFactory.java
- src/main/resources/org/jenkinsci/plugins/mesos/MesosAgentSpecTemplate/ContainerInfo/config.jelly
- src/main/resources/org/jenkinsci/plugins/mesos/MesosAgentSpecTemplate/ContainerInfo/help-networking.html
- src/test/java/org/jenkinsci/plugins/mesos/fixture/AgentSpecMother.java
Summary:
This re-introduces the networking mode for the plugin. We use the enum
from the Apache Mesos protobufs.
> Configure networking mode.

- build.gradle
- src/main/java/org/jenkinsci/plugins/mesos/MesosAgentSpecTemplate.java
- src/main/java/org/jenkinsci/plugins/mesos/config/models/faultdomain/Any.java
- src/main/java/org/jenkinsci/plugins/mesos/config/models/faultdomain/DomainFilterModel.java
- src/main/java/org/jenkinsci/plugins/mesos/config/models/faultdomain/DomainFilterModelDescriptor.java
- src/main/java/org/jenkinsci/plugins/mesos/config/models/faultdomain/Home.java
- src/main/java/org/jenkinsci/plugins/mesos/config/models/faultdomain/StringDomainFilter.java
- src/main/resources/org/jenkinsci/plugins/mesos/MesosAgentSpecTemplate/config.jelly
- src/main/resources/org/jenkinsci/plugins/mesos/MesosAgentSpecTemplate/help-domainFilterModel.html
- src/main/resources/org/jenkinsci/plugins/mesos/config/models/faultdomain/DomainFilterModel/config.jelly
- src/main/resources/org/jenkinsci/plugins/mesos/config/models/faultdomain/StringDomainFilter/config-detail.jelly
Summary:
This change enables an operator to choose the home region, any domain or
a custom filter to decide which offers from which fault domain should be
considered.
> Select fault domain filter.

- build.gradle
- src/main/java/org/jenkinsci/plugins/mesos/MesosApi.java
- src/main/java/org/jenkinsci/plugins/mesos/api/LaunchCommandBuilder.java
Summary:
This pulls in the new USI verison >= 0.1.26 that comes with suppress and
revive support known from Marathon 1.9.
Depends on mesosphere/usi#131
> Use new USI interface with scheduler factory.

- .github/workflows/gradle.yml
- Jenkinsfile
- README.md
- build.gradle
- ci/install_docker.sh
- ci/install_mesos.sh
- src/test/java/org/jenkinsci/plugins/mesos/MesosCloudTest.java
- src/test/java/org/jenkinsci/plugins/mesos/integration/DockerAgentTest.java
- src/test/java/org/jenkinsci/plugins/mesos/integration/IntegrationTest.java
- src/test/java/org/jenkinsci/plugins/mesos/integration/MesosApiTest.java
- src/test/java/org/jenkinsci/plugins/mesos/integration/MesosCloudProvisionTest.java
- src/test/java/org/jenkinsci/plugins/mesos/integration/MesosJenkinsAgentLifecycleTest.java
Summary:
This will use Github Actions to run all tests. Jenkins will run checks without integration tests.
> Build and test on Github.

- src/main/java/org/jenkinsci/plugins/mesos/MesosJenkinsAgent.java
- src/main/resources/org/jenkinsci/plugins/mesos/MesosJenkinsAgent/configure-entries.jelly
A simple fix for a minor issue; but I don't like seeing error pages.
> Jenkins throws exceptions showing configuration for a Mesos Agent (#407)
