src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java
'Safe shutdown mode' in Jenkins is a state where no further builds will be performed, but Jenkins will wait for the builds are already in progress to complete before shutting down. 
There is no point in provisioning a slave if Jenkins is in safe shutdown mode since the build won't be picked up by the slave anyways. This fix addresses that.
=> Make sure Jenkins is not in safe shutdown mode before provisioning

src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly
Please refer to https://issues.jenkins-ci.org/browse/JENKINS-26321 for details.
=> [JENKINS-26321] Booleans for isReadOnly (Volume), isExtract and isExecutable (URI) are not handled properly

README.md, pom.xml, src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-parameters.html
This will allow the use of Docker parameters which is available in mesos 0.21.0. This also brings the plugin up-to-date with the latest mesos release. My use-case has been to allow the sharing of data containers among slaves on a particular node. Specifically not requiring tools and maven dependencies to have long download times for each build. There are likely other use-cases that I have yet to explore, but this has been tested in my Jenkins instance.
=> [JENKINS-26236] Add Docker parameter functionality

.gitignore, README.md, Vagrantfile, pom.xml
Upgraded to build with latest versions of Mesos 0.21.1 and Jenkins LTS (at least the Long Term Support release) 1.580.2.
Required some updating to Vagrantfile as well, which additionally resulted in fix for issue #76, plus now has the option to use the local plugin source instead of explicit release version if desired within the VM. This is helpful for some testing in VM, but as per previous code still defaults to released version of plugin (now latest version as well - 0.5.0)
=> Upgraded to build with Mesos 0.21.1

pom.xml
1.565.3 core version has 1.106 hpi plugin version https://github.com/jenkinsci/jenkins/blob/8b3e53c7e55ab888de637586f08398524bcdcfc6/pom.xml#L493 no need to define it now
=> hpi version is enough with current core

.gitignore, src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/Mesos.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/java/org/jenkinsci/plugins/mesos/MesosComputer.java, src/main/java/org/jenkinsci/plugins/mesos/MesosComputerLauncher.java, src/main/java/org/jenkinsci/plugins/mesos/MesosImpl.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlave.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java
This is to address issue 94:
https://github.com/jenkinsci/mesos-plugin/issues/94
The Mesos object was written to be a singleton
even though Jenkins supports defining more than one.
In my case, I was trying to control 2 different clusters
(with 2 different slave tags).  Because the MesosImpl gets created by
whichever slave happens to launch first, slave tags from the other cluster
would launch in the wrong place.
While I don't LOVE this implementation, it seemed the least minimal
impact to a larger refactoring.  I basically pass a reference for the
MesosCloud to the MesosSlave.  Then I changed the Mesos.getInstance()
to take a parameter which is used as a key in a Map keyed by MesosCloud to
find the correct MesosImpl.  It was necessary to externalize the MesosImpl
inner-class to get it to …
=> Fix support for multiple Mesos Clouds

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
I added a web UI field so that Mesos registers the location of the Jenkins UI. If this is not available at runtime, then the WebUI will not register.
=> Adding WebUI field to Framework Info

pom.xml, src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly
This pull request adds a new feature described in https://issues.jenkins-ci.org/browse/JENKINS-26324
Changes made:
* ~~Updated Mesos libs to 0.21.0 and HPI plugin to 1.106~~
* HOST and BRIDGE networking for docker containers can now be configured
* Port mappings for those are also possible (if Host Port is left empty, a random Port on the host is used)
~~Snuck in changes (I tried to keep commits atomic, but this happened anyway):~~
* ~~Slave name on Jenkins is now dependent on label (which might not always be good); See: String name = slaveInfo.getLabelString() + "-" + UUID.randomUUID().toString();~~
* ~~The hostname of the docker container is set to the name of the slave~~
* ~~An Exception is now logged if something happens in createMesosTask()~~
* ~~HUDSON_HOME changed from jenkins to …
=> [JENKINS-26324] Add configurable bridged network mode for Docker containers

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/MesosRetentionStrategy.java
Thread Leak:
When no Task was created in Mesos (due to connection error to Mesos Master or no resources available) there was no "signal" sent to the waiting MesosSlaveLauncher to finish waiting. Therefore the thread count in the Java VM increased drastically.
Deadlock:
When terminating Slaves there is a possible deadlock when the Retention check starts. We observed and experienced this two times in the last weeks. Same issue (and solution) as here (https://issues.jenkins-ci.org/browse/JENKINS-22558), but different plugin.
=> Fix thread leak and deadlock on terminating slaves

src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java
The stored protobufs pre-0.7.0 basically deserialed the new fields
as nulls.  By adding some guards on the getters we avoid 2 NPEs.
when getting the port mappings (want empty collection) and
also when getting networking definition (use default bridge value).
Fixes https://github.com/jenkinsci/mesos-plugin/issues/113 and https://github.com/jenkinsci/mesos-plugin/issues/111
Please cut 0.7.1 ASAP.
Thanks!
=> fix NPE in 0.7.0 with old serialized data

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
Lowering the logging level from INFO to FINE for a few items.
The noisiest one is the 'not matching slave' message in mesos environments
where only a few of the slaves are jenkins candidates.  The non-matching ones
dump many large json objects into the logs which really falls more into
the debugging camp hence the lower level
=> reduce logging level for some status things

src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java
With the fix to support multiple MesosClouds (https://github.com/jenkinsci/mesos-plugin/pull/96) with a HashMap lookup keyed on MesosCloud objects, I neglected to add equals/hashcode.  This means that if you hit 'save', but actually not change anything we go down the path of resetting the framework (which actually registers a second framework and leaves the first one in-tact) rather than calling the ``updateScheduler`` method.  Without hashcode being properly implemented, the Mesos.getInstance() lookup will always fail.  Since this code only seems to care about the master string (or master zk string), that is what I based the hashcode/equals code on.
// Restart the scheduler if the master has changed or a scheduler is not up.
if (!master.equals(staticMaster) || …
=> fix hashcode lookup resetting framework on save

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
When more than one MesosCloud instance exist, in JenkinsScheduler#supervise the SUPERVISOR_LOCK is locked once but released too many times. Therefore an IllegalMonitorStateException is thrown. Moving the call to unlock outside the loop fixes this issue.
Should fix #129
=> SUPERVISOR_LOCK.unlock() should be outside the loop

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
This status TASK_ERROR has been introduced in mesos 0.21, but is only sent starting from 0.22.
The PR only add the new status to the JenkinsScheduler.java in the case block of the statusUpdate() function. This avoids a Java exception crashing the scheduler.
It may need future "functional" adaptations regarding why such a status is sent by mesos.
https://github.com/jenkinsci/mesos-plugin/issues/125
=> Take into account new mesos status TASK_ERROR

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-customDockerCommandShell.html, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-useCustomDockerCommandShell.html, src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java
This PR addresses https://issues.jenkins-ci.org/browse/JENKINS-28641 which makes it possible to configure the use of a custom command shell when executing a docker based slave, which is helpful when trying to run a docker-in-docker / dind image.
This issue was also raised in the google group here:
https://groups.google.com/forum/#!topic/jenkins-mesos/JgFCmqOO7Fg
It is a rebased, squashed and merged version of https://github.com/jenkinsci/mesos-plugin/pull/112 which was closed in error
Ping @nikore @maselvaraj @bacoboy
=> JENKINS-28641 - Allow for configuration of a custom command shell when using docker

pom.xml, src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCleanupThread.java, src/main/java/org/jenkinsci/plugins/mesos/MesosComputer.java, src/main/java/org/jenkinsci/plugins/mesos/MesosComputerLauncher.java, src/main/java/org/jenkinsci/plugins/mesos/MesosRetentionStrategy.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSingleUseSlave.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlave.java, src/main/resources/org/jenkinsci/plugins/mesos/Messages.properties, src/test/java/org/jenkinsci/plugins/mesos/MesosRetentionStrategyTest.java
Fixes #48
Based off the JClouds Jenkins plugin's implementation. The slave, on teardown, will mark temporarily offline, and thus no longer take any jobs. The Mesos retention strategy will then set it as pending deletion after the idle period to protect against post-build actions from terminating the slave too soon. The final step is the asynchronous period work in MesosCleanupTask which will terminate the pending deletion slave.
=> Support one off slaves on the job level for mesos slaves.

pom.xml, src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly, src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java
From 0.22.x Mesos implemented the force_pull_image flag but set it's default value to false. This means a 'latest' tag is ignored and the docker image is never pulled again, regardless of whether it has been updated on the docker registry.
Requires minimum Mesos 0.22.1.
Referencing these issues...
https://github.com/jenkinsci/mesos-plugin/issues/89
https://github.com/jenkinsci/mesos-plugin/issues/132
=> implemented mesos force_pull_image

src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java
If label is empty then mesos slaves will be used for all jobs without label requirements
In a mesos-only Jenkins installation it is confusing for users to create jobs
that sit there because the label is by default empty and never get scheduled in Mesos.
If the Jenkins config for mesos cloud has an empty label then the mesos slaves
are added to the default pool for any job without label requirements
@reviewbybees
=> Allow running all jobs in mesos slaves

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
Split from #179 
If any RuntimeException is raised during Scheduler execution, the object
was left in a corrupt state with running == true and driver != null.
The previous implementation would let any RuntimeException kill the
thread without any trace of it. Now, it is properly logged when it
happens and leave the scheduler in a correct state.
@reviewbybees
=> Wrap JenkinsScheduler run body in a try/catch/finally.

pom.xml, src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-credentialsId.html
This pull request provides integration with credentials plugin to replace framework principal/secret.
Credentials plugin provides a central facility to manage credentials and to update them only once if needed.
The motivation for this change is to provide the ability to update programmatically the mesos credentials without touching the cloud configuration, which may have been altered by an administrator. The current implementation doesn't allow that in an easy way, as you need to post the whole configuration.
=> Integration with credentials plugin

src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java
When running many slave types, seeing everything as:
mesos-jenkins-453c7f5c-4c70-46fa-a272-cf939852f321
mesos-jenkins-7e2a8b6a-66e0-4cbc-87ec-cf06a4693a7e
mesos-jenkins-06e6dd76-20e0-4b69-8fef-47d039d822f0
It becomes difficult to see what is what.
This change adds the jenkins label into the name so it looks more like this:
mesos-foo-slave-453c7f5c-4c70-46fa-a272-cf939852f321
mesos-bar-slave-7e2a8b6a-66e0-4cbc-87ec-cf06a4693a7e
mesos-baz-slave-06e6dd76-20e0-4b69-8fef-47d039d822f0
where the jenkins labels are `foo-slave`, `bar-slave` and `baz-slave`
=> Add jenkins label to mesos slave task's name

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java
This ensures port order is deterministic and should prevent any flaky behaviour for testing.
e.g. https://jenkins.ci.cloudbees.com/job/plugins/job/mesos-plugin/org.jenkins-ci.plugins$mesos/324/testReport/junit/org.jenkinsci.plugins.mesos/JenkinsSchedulerTest/testFindPortsToUseSamePortNumber/
@reviewbybees
=> Modify JenkinsScheduler#findPortsToUse to return a SortedSet structure instead of a List.

src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly
If the label is set to empty string, when coming back to the configuration, the field is set to 'mesos'.
This change will set the value to mesos only if it is a new SlaveInfo
@reviewbybees esp. @carlossg
=> Fix roundtrip on configuration if the label is set to empty string

src/main/java/org/jenkinsci/plugins/mesos/MesosSlave.java
Recent JVMs determine automatically the max heap by taking about 1/4
of the available memory.
http://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/parallel.html#default_heap_size
The problem is that it takes as reference the host memory through
RLIMIT_AS flag value, and not the value defined by the cgroup it belongs
to.
As a consequence, if -Xmx is not explicitely specified and set to
relevant value, build processes may get killed by OOM-killer.
This takes the executor memory and set it as maximum heap size for any
forked jvm process which is what the user wants in most cases.
=> Set _JAVA_OPTIONS to use the executor memory as max heap

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly, src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java
this change prevents offer starvation by:
* rejecting offers for longer period if no slave is queued
* calling reviveOffers when adding a slave to queue
this is necessary when running a lot of frameworks on a mesos cluster.
the rejectOfferDuration is configurable and defaults to 10min.
this is basically the same change made in marathon and chronos a few weeks ago.
see https://github.com/mesosphere/marathon/pull/1949 for further details.
=> prevent offer starvation

src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java
When jenkins slaves have multiple labels, there are spaces between the labels.  When this is translated directly into the mesos jenkins slave name it causes problems:
- When running slave.jar, jenkins does not enclose the name in quotes, so if there are spaces they are treated as separate command line parameters and this causes the java command to fail
- The mesos jenkins slave name is translated directly into a path so spaces and the ellipsis at the end make for difficult paths to work with.
This change removes any spaces from the label string and uses "left" instead of "abbreviate" to truncate the jenkins slave name to 63 characters instead of abbreviating it with an ellipsis.
=> Update jenkins slave naming to fix issues with spaces

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/Mesos.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/java/org/jenkinsci/plugins/mesos/MesosComputerLauncher.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-role.html, src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java
This is a fix for PR #155 and refs issue #68.
1. It accepts resources from `*` AND the specified role.
2. It launches tasks for offers with multiple sets of resources.
An example:
Given, you want to start a jenkins-slave with 4 cpus and 1024 mem.
Given, mesos sends an offer from a slave with:
* 2 cpus for role `jenkins`
* 3 cpus for role `*`
* 2048 mem for role `*`
The framework now will pick the 2 cpus for `jenkins`, 2 cpus for `*` and 1024 mem for `*` to start the task.
=> Framework roles

pom.xml
This has no practical use and clutters target/ folder.
=> Remove useless call to dependency-plugin

src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java
Otherwise, will throw a NPE
```
java.lang.NullPointerException
at com.cloudbees.plugins.credentials.matchers.IdMatcher.<init>(IdMatcher.java:49)
at com.cloudbees.plugins.credentials.CredentialsMatchers.withId(CredentialsMatchers.java:112)
at org.jenkinsci.plugins.mesos.MesosCloud.getCredentials(MesosCloud.java:298)
at org.jenkinsci.plugins.mesos.JenkinsScheduler$1.run(JenkinsScheduler.java:127)
at java.lang.Thread.run(Thread.java:745)
```
=> getCredentials should return null if credentialsId is null

src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java
As credentialsId is @DataBoundSetter, it isn't part of the constructor, so it must be copied separately.
@reviewbybees
=> Fix the copy constructor

src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java
Return slave attributes of a slave with no label (instead of null) when the request is for a slave with no label.
=> Fix getSlaveAttributeForLabel when labelName is null

src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly
We have seen instances where the slave info is deleted from the master and the slave keeps running forever
probably due to some race condition
Default to no reconnect, but can be overriden
@reviewbybees
=> Slaves should not try to reconnect

src/main/java/org/jenkinsci/plugins/mesos/MesosComputerLauncher.java
If the slave is not connected, Jenkins might try to launch additional slaves which results in over-provisioning slaves and reserving additional resources in the mesos cluster.
@reviewbybees
=> Wait for slave to come online to avoid provisioning of additional slaves

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/Mesos.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/java/org/jenkinsci/plugins/mesos/MesosImpl.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java
Added a Garbage Collector to stop the scheduler and remove the mesos framework in case the cloud gets removed.
Doing so, I found out that there was a problem related to credentialsId and usage of @DataBoundSetter : when the scheduler is restarted after constructor call (onDemandRegistration=false), credentialsId value is not yet set and this can cause a duplicate framework registration. So the field initialization has been moved to constructor.
Last, added equals/hashCode implementations to MesosSlaveInfo and embedded classes, as these are necessary to compare MesosCloud instances, and these are used in Mesos#getInstance to prevent building duplicate MesosImpl instances.
@reviewbybees
=> Fix another case of duplicate framework registration

pom.xml, src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/Mesos.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly
We require now mesos 0.27.0 to build the plugin but we retain runtime compatibility with versions older than 0.25.0 by using reflection for the changed API.
External containerizer has been deprecated in Mesos, so support has been removed from the plugin.
@reviewbybees
=> Update mesos dependency to 0.27.0

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
Jenkins-slave  can consume all of allocated memory via -Xmx switch. Bugfix:. Only slave memory amount should be assigned.
=> jenkins slave memory fix

src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosSlaveInfo/config.jelly, src/main/resources/org/jenkinsci/plugins/mesos/MesosSlaveInfo/help-minExecutors.html, src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java
Current behavior won't change (default value set to 1) and the update of the workload has been modified to take in account this parameter.
=> Add a minimum number of executors per slave #232

src/main/java/org/jenkinsci/plugins/mesos/Mesos.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlave.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/help-cloudID.html
Saving a new MesosCloud config causes all running tasks to terminate because the Jenkins scheduler is being needlessly restarted upon every config change. These changes address this problem and allow the Jenkins scheduler to stay running when config changes are made to the MesosCloud.
The root cause of this issue was the GarbageCollector in Mesos.Java incorrectly removing modified (not removed) clouds - this is a consequence of using mutable keys in a HashMap. As a fix, I have implemented a cloudID that serves as a unique identifier for each MesosCloud. This allows for "modified" clouds (i.e. same cloud with a changed description or slaveInfo) to be recognized and not accidentally removed by the GarbageCollector.
I also fixed a NPE occuring in the matchesLabel method.
=> Fix: Modifying MesosCloud Configuration Kills Running Jobs

pom.xml, src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosSlaveInfo/ContainerInfo/config.jelly, src/main/resources/org/jenkinsci/plugins/mesos/MesosSlaveInfo/NetworkInfo/config.jelly, src/main/resources/org/jenkinsci/plugins/mesos/MesosSlaveInfo/NetworkInfo/help-networkName.html, src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java, src/test/java/org/jenkinsci/plugins/mesos/MesosSlaveInfoTest.java
This patch enables virtual networking through the use of overlay networks. Overlay networks enable you to provide each container in the system with a unique IP address (“IP-per-container”) with isolation guarantees amongst subnets. This patch adds the capability to specify NetworkInfo name when configuring containerInfo, allowing for a container to be assigned a unique ip address in a specific network.
=> Add support for overlay networks 

src/main/resources/org/jenkinsci/plugins/mesos/MesosComputer/mesos-slave-agent.jnlp.jelly
#258 Passing ${app.rootUrlFromRequest} and ${rootUrl} as -url arguments make it more broadly compatible.
I ordered them http, then https, and it works in my environment, where it didn't before.
=> Passing ${app.rootUrlFromRequest} and ${rootUrl} as -url arguments

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java
If a Mesos scheduler is configured with a role, the scheduler receives offers for resources under that defined role (or the default role).
Currently, the code that builds tasks for execution doesn't include any role attached in the offer for assigned port resources.
This PR ensures that the role for port resources on the offer is used, just like it is for cpu and mem.
This problem was manifesting itself with errors in both the Jenkins and mesos-master logs and a number of failed Jenkins slaves would appear in the Jenkins UI, e.g.:
```
Sending status update TASK_ERROR for task mesos-jenkins-506c01240453427bb20f1d3dff26b718-mesos-ultra-e2e of framework 7ef79e0d-1cc1-4880-ad98-7fb0329fa816-0003 'Total resources cpus(jenkins_sg):1.1; mem(jenkins_sg):6899.2; ports(*):[31000-31000] required by …
```
=> Ensure task is launched with appropriate roles on ports from offer.

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/Mesos.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/java/org/jenkinsci/plugins/mesos/MesosComputerLauncher.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlave.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosSlaveInfo/config.jelly, src/main/resources/org/jenkinsci/plugins/mesos/MesosSlaveInfo/help-diskNeeded.html, src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java, src/test/java/org/jenkinsci/plugins/mesos/MesosSlaveInfoTest.java
This option could be customized at slave level and hence
plugin would only accept resources that has the specified
amount in MB as Disk resource available. The option is
ignored for Docker containerizer and if the value is set
to 0.
This opens up up the killing of mesos slave if the slave
uses more that alloted amount of disk space by setting
--isolation with disk/du and
--enforce-container-disk-quota
=> Add option to specify disk resource.

Jenkinsfile, pom.xml, src/main/java/org/jenkinsci/plugins/mesos/MesosRetentionStrategy.java
It includes #309 for testing purposes and includes a hotfix for https://issues.jenkins-ci.org/browse/JENKINS-49117 to make the plugin compatible with Jenkins 2.102+
@reviewbybees @jglick
=> [JENKINS-49117] - Stop serializing ReentrantLocks to the disk

Jenkinsfile, pom.xml, src/main/java/org/jenkinsci/plugins/mesos/MesosRetentionStrategy.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java, src/test/java/org/jenkinsci/plugins/mesos/MesosCloudTest.java, src/test/resources/org/jenkinsci/plugins/mesos/MesosCloudTest/oldData/config.xml
[JENKINS-50303](https://issues.jenkins-ci.org/browse/JENKINS-50303). Follows up #310.
Does not attempt to load historical `slaveAttributes` settings. They will just need to be reconfigured. Since there are barely over a thousand registered users of this plugin, and this field was in an **Advanced** block to begin with, I figure release notes should suffice.
@reviewbybees esp. @oleg-nenashev @Vlatombe
=> [JENKINS-50303] Using XStream to serialize a JSONObject was never advisable and as of 2.102 is forbidden

pom.xml
Guava is bundled in Jenkins and at a much lower version, so this is
asking for issue to happen.  e.g. [JENKINS-51889](https://issues.jenkins-ci.org/browse/JENKINS-51889) jenkinsci/workflow-cps-plugin#231
=> Do not use a higher version of Guava than Jenkins.

src/main/resources/org/jenkinsci/plugins/mesos/MesosSlaveInfo/ContainerInfo/config.jelly
The option to put the USER-type network is added in the containerInfo configuration file.
=> Add radioBlock for USER networking on config.jelly

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java
Offers are suppressed when there is no pending work and revived when there is. The code guards against the cases that either suppress (by calling on subsequent offer reception) or revived (by calling it periodically) are dropped.
=> Added offer suppression support.

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java
No need to suppress when there were no offers received.
=> Fixed redundant suppress.

src/main/java/org/jenkinsci/plugins/mesos/MesosRetentionStrategy.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSingleUseSlave.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlave.java, src/test/java/org/jenkinsci/plugins/mesos/MesosRetentionStrategyTest.java
* Add Single Use property to MesosSlave
Single-use agents are marked offline and then still wait for
idle timeout before being deleted. This commit adds a new
property to MesosSlave to mark single-use agents. This is
read during the retention check and used to mark a cluster
for deletion.
* Order matters
* Add locks around new property
* Add test for single use and retention policy
* Sync pending delete as well
=> Add Single Use property to MesosSlave (#16)

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java
Pending builds might be enqueued on the already connected executors, so
the scheduler shouldn't be waiting for offers for those. Offers are only
relevant when the node provisioner enques a slave provision request on
to the scheduler.
=> Suppress/long decline should not directly look at pending builds.

src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java
Summary:
This resolves the `isDind` flag on the container info to enable a config
migration from 0.x to 1.1.
JIRA issues: DCOS_OSS-5586
=> Migrate Dind flag.

README.md
Let's use the official ci.jenkins.io build status.
=> Update build badge link.

build.gradle, src/main/java/org/jenkinsci/plugins/mesos/MesosApi.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/java/org/jenkinsci/plugins/mesos/Metrics.java, src/test/java/org/jenkinsci/plugins/mesos/MesosCloudDescriptorTest.java, src/test/java/org/jenkinsci/plugins/mesos/MetricsTest.java, src/test/java/org/jenkinsci/plugins/mesos/integration/DockerAgentTest.java, src/test/java/org/jenkinsci/plugins/mesos/integration/MesosApiTest.java
Summary:
This uses the `MasterDetector` from mesosphere/usi#118 to infer the
proper Mesos address from either a Zookeeper server list and path or an
HTTP address.
JIRA issues: DCOS_OSS-5588
=> Detect Mesos master URL.

src/main/java/org/jenkinsci/plugins/mesos/MesosUtils.java, src/test/java/org/jenkinsci/plugins/mesos/MesosUtilsTest.java
Before this change, if you used the mesos plugin option 'Docker Image Can Be Customized'
and the resulting task name was less than 64 characters it could happen that the docker
image name contained invalid characters both for the task name and the docker hostname.
For example a custom label:foo/bar:latest would fail as a task name because / is invalid
in a task name since it breaks the directory structure. It would also fail as a docker
hostname since it needs to comply with RFC 1123 hostnames
Original commit was to fix #251
Making the change to the buildNodeName() makes it consistent across the code
=> Replace invalid hostname characters for task names and docker hostname

src/main/java/org/jenkinsci/plugins/mesos/MesosAgentSpecTemplate.java, src/main/java/org/jenkinsci/plugins/mesos/MesosSlaveInfo.java, src/main/java/org/jenkinsci/plugins/mesos/api/LaunchCommandBuilder.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosAgentSpecTemplate/ContainerInfo/config.jelly, src/main/resources/org/jenkinsci/plugins/mesos/MesosAgentSpecTemplate/ContainerInfo/help-overrideShellCommand.html, src/main/resources/org/jenkinsci/plugins/mesos/MesosAgentSpecTemplate/config.jelly, src/main/resources/org/jenkinsci/plugins/mesos/MesosAgentSpecTemplate/help-agentCommandStyle.html, src/test/java/org/jenkinsci/plugins/mesos/fixture/AgentSpecMother.java
Summary:
When the Jenkins agent is launched on a Windows node the command differs slightly
from the Linux command. This patch introduces a command style which defaults to Linux.
=> Define agent shell command style.

dcos/conf/jenkins/configuration.yaml
Summary:
This patch provides an example configuration for Linux and Windows
nodes.
Depends on #377.
JIRA issues: DCOS-61124
=> Configure Linux and Windows agents.

build.gradle, dcos/conf/jenkins/configuration.yaml, dcos/conf/plugins.conf, dcos/jenkins-app.json, src/main/java/org/jenkinsci/plugins/mesos/MesosApi.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/main/java/org/jenkinsci/plugins/mesos/MesosProvisioningStrategy.java, src/main/java/org/jenkinsci/plugins/mesos/config/models/faultdomain/StringDomainFilter.java, src/main/resources/org/jenkinsci/plugins/mesos/MesosCloud/config.jelly, src/test/java/org/jenkinsci/plugins/mesos/MesosCloudTest.java, src/test/java/org/jenkinsci/plugins/mesos/integration/DockerAgentTest.java, src/test/java/org/jenkinsci/plugins/mesos/integration/MesosCloudProvisionTest.java, src/test/java/org/jenkinsci/plugins/mesos/integration/MesosJenkinsAgentLifecycleTest.java
Summary:
The plugin would create a new framework ID and a new Mesos connection if the config was
changed. This patch persists the framework ID in the config as a read only parameter.
Furthermore the plugin is now partition and region aware to support Windows fault domains.
We also test the serialization and deserialization.
Jira issues: DCOS_OSS-5831, DCOS_OSS-5817
=> Reuse Mesos session.

dcos/conf/plugins.conf
Summary:
The Docker build would fail because the name of the pre-installed
pipeline plugin was wring.
=> Rename plugin dependency.

dcos/conf/plugins.conf
Summary:
It's pulled in by downstream dependencies.
=> Remove Jackson API plugin.

build.gradle, src/main/java/org/jenkinsci/plugins/mesos/MesosApi.java, src/main/java/org/jenkinsci/plugins/mesos/api/LaunchCommandBuilder.java
Summary:
Changes to the Jenkins URL and agent user would have no effect since the
Mesos API needs to reconnect to Mesos and the URL need to be overriden
in case the connection was cached.
JIRA issues: DCOS_OSS-5933
=> Change Mesos API on configuration change.

README.md, build.gradle, src/main/java/org/jenkinsci/plugins/mesos/api/RunTemplateFactory.java, src/test/java/org/jenkinsci/plugins/mesos/fixture/AgentSpecMother.java, src/test/java/org/jenkinsci/plugins/mesos/integration/DockerAgentTest.java
Summary:
If a Docker container is defined we pass the agent command as arguments
to the container. This way users will not have override the shell command.
Relates to https://github.com/mesosphere/dcos-jenkins-service/pull/319.
JIRA issues: DCOS_OSS-5937
=> Use Docker entrypoint.

src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java, src/main/java/org/jenkinsci/plugins/mesos/MesosCloud.java, src/test/java/org/jenkinsci/plugins/mesos/JenkinsSchedulerTest.java
- In situation where developers are using Configuration as Code, and specifying mesos label in scripted DSL (ex: mesos:myDockerContainer) would require label creation for N number of docker containers to be configured in Mesos Cloud config. Was observing in this case, slave attributes were not being honored and offers were accepted regardless.
- Introduce enhancement to label matching to retrieve attributes, so in event of match on primary label configured as default (ex: mesos) for request(mesos:myDockerContainer) would match based on enhancement which first attempts to get exact match, then trims label provided to find a match also marked as default or otherwise, like previously, just return the provided label's attributes. 
- this enhancement provides to maintainers the ability to …
=> select default mesos slave attributes on label match partial match

Dockerfile.agent, Jenkinsfile, build.gradle, dcos-testing/conf/jenkins/configuration.yaml, src/main/java/org/jenkinsci/plugins/mesos/api/RunTemplateFactory.java, src/test/java/org/jenkinsci/plugins/mesos/fixture/AgentSpecMother.java
Summary:
The previous image would try to start a Docker daemon in a Docker container which itself is
running in a Docker container on the CI. This could work but just takes too much configuration.
We are running a simple client instead.
=> Fix DockerAgentTest.
